# Generated by Django 5.0.7 on 2024-07-25 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('red', 'high'), ('green', 'normal'), ('blue', 'low')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
